name: Black Duck Rapid Scan

# Run Rapid Scan on all pull requests and pushes to a main branch
on:
  pull_request:
    branches:
      - master
  push:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up JDK 11 in runtime environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Run Synopsys Detect
      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.2.0
        # This server does not require a local CA Cert
        #env:
        #  NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
        # Enable diagnostic mode
        env:
          DETECT_DIAGNOSTIC: true
        #  DETECT_DIAGNOSTIC_EXTENDED: true
        with:
            scan-mode: RAPID
            github-token: ${{ secrets.GITHUB_TOKEN }}
            detect-version: 7.9.0
            blackduck-url: ${{ secrets.BLACKDUCK_URL }}
            blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
